name: ride_with_passion
description: A new Flutter project.

version: 1.0.0+01000001

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: 1.0.1

  #https://pub.dev/packages/get_it
  get_it: ^4.0.0

  #https://pub.dev/packages/get
  get: ^2.0.10

  #https://pub.dev/packages/provider_architecture
  provider_architecture: ^1.1.1+1

  #https://pub.dev/packages/logger
  logger: ^0.8.3

  #https://pub.dev/packages/rxdart
  rxdart: ^0.23.1

  #https://pub.dev/packages/json_annotation
  #https://github.com/dart-lang/json_serializable/tree/master/example
  json_annotation: ^3.0.0

  #https://pub.dev/packages/validators
  validators: ^2.0.0

  #https://pub.dev/packages/firebase_auth
  firebase_auth: 0.15.3

  #https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^0.13.5 #not the newest version because of issues with dex files

  firebase_core: 0.4.4

  #https://pub.dev/packages/font_awesome_flutter#-installing-tab-
  font_awesome_flutter: ^8.7.0

  #https://pub.dev/packages/cached_network_image
  cached_network_image: ^2.0.0

  #https://pub.dev/packages/geolocator
  geolocator: ^5.3.0

  open_file: ^3.0.1

  http: ^0.12.0+4

  google_maps_flutter: 0.5.27+1

  background_fetch: ^0.5.1

  shared_preferences: ^0.5.7

  path_provider: ^1.4.5

  draggable_scrollbar: ^0.0.4

  #https://pub.dev/packages/carousel_slider
  carousel_slider: ^1.4.1

  #https://pub.dev/packages/photo_view
  photo_view: ^0.9.2

  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  #https://pub.dev/packages/json_serializable#-readme-tab-
  json_serializable: ^3.2.5
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/bike_challenges.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ic_login.png
    - assets/ic_appbar.png
    - assets/bike_icon.png
    - assets/images/
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
